### ISSUE TITLE
Bug: Styling interfaces with prettier breaks argument comparison

### ISSUE THREAD

**Issue by papeldeorigami** [amit221/es6-interface#2]
**Steps to reproduce**: just run prettier with default settings on the test/interface.js file and one of the tests will break. 

The attached images show the differences. After a few try and error, found out it was because of the addition of extra spaces between the curly brackets. The other changes were not significant.
![error](https://user-images.githubusercontent.com/1676528/117910494-6bf3e180-b2b2-11eb-84db-5f906dcb2660.png)
![changes](https://user-images.githubusercontent.com/1676528/117910501-6d250e80-b2b2-11eb-8060-a35fae9628aa.png)

**Comment by amit221** [comment]
Hi @papeldeorigami 
I think this change is really nice. (also the pull request)
I will check it out more thoroughly in the next few days and hope to merge it(:
