### ISSUE TITLE
Feature request: support for shorthand es2015 object methods

### ISSUE THREAD

**Issue by papeldeorigami** [amit221/es6-interface#4]
As documented in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
It is now possible to declare object methods using this syntax:
```js
const obj = {
  foo() {
    return 'bar';
  }
};
```

**Comment by papeldeorigami** [comment]
@amit221 I have already prepared another commit to implement this feature, but please have a look at https://github.com/amit221/es6-interface/pull/3 first. I'd prefer to build on that code. Here is my commit, just in case you want to take a look and maybe provide me with some feedback: https://github.com/codehashi/es6-interface/commit/16a6ab4e86a3e9fc034711ea1c8fdf06377b6ba8

**Comment by amit221** [comment]
merged
